# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IgnoreMe < Formula
  desc "A smart and beautiful CLI tool for .gitignore generation"
  homepage "https://github.com/erdemkosk/ignore-me"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erdemkosk/ignore-me/releases/download/v1.0.2/ignore-me_Darwin_x86_64.tar.gz"
      sha256 "688cf07a277439f7073acb1a99f06152ea688785a23741fb2eea72850e943214"

      def install
        bin.install "ignore-me"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erdemkosk/ignore-me/releases/download/v1.0.2/ignore-me_Darwin_arm64.tar.gz"
      sha256 "e4d44a6bae66cc3c94cac69928d4df60eb6830e5848734a688d2bb50f1075a88"

      def install
        bin.install "ignore-me"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erdemkosk/ignore-me/releases/download/v1.0.2/ignore-me_Linux_x86_64.tar.gz"
        sha256 "cce715b29a5675e2ef4c9f8280028f671f67dd95a1954632e6437647d6217d8b"

        def install
          bin.install "ignore-me"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erdemkosk/ignore-me/releases/download/v1.0.2/ignore-me_Linux_arm64.tar.gz"
        sha256 "fa77d3daf1f90fb7140cda004e3397f62269d6eda1d16fce7a091308afde6136"

        def install
          bin.install "ignore-me"
        end
      end
    end
  end

  test do
    system "#{bin}/ignore-me --version"
  end
end
