# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IgnoreMe < Formula
  desc "A smart and beautiful CLI tool for .gitignore generation"
  homepage "https://github.com/erdemkosk/ignore-me"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erdemkosk/ignore-me/releases/download/v1.0.1/ignore-me_Darwin_x86_64.tar.gz"
      sha256 "ce16183fd43311877e96a04d1f25d180d28793af119e6d72fca4e2d78bbccd31"

      def install
        bin.install "ignore-me"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erdemkosk/ignore-me/releases/download/v1.0.1/ignore-me_Darwin_arm64.tar.gz"
      sha256 "a6b3177242e72dc7c3850f6f3eab50f3f19d10d452cc194910ddc290c73d29d8"

      def install
        bin.install "ignore-me"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erdemkosk/ignore-me/releases/download/v1.0.1/ignore-me_Linux_x86_64.tar.gz"
        sha256 "76f843d9820f345a6dde78d712c6c99da187ac01f95af2b2e374b01dff7330c2"

        def install
          bin.install "ignore-me"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erdemkosk/ignore-me/releases/download/v1.0.1/ignore-me_Linux_arm64.tar.gz"
        sha256 "f0e2c1bee4546aff1765fe32ad70c0831382721eeebc097ae2309101f1415c35"

        def install
          bin.install "ignore-me"
        end
      end
    end
  end

  test do
    system "#{bin}/ignore-me --version"
  end
end
